site_name: Makester
site_url: https://loum.github.io/makester/
nav:
  - Home: index.md
  - Getting started: getting-started.md
theme:
  name: material
  palette:
    # Palette toggle for light mode
    - scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
